version: "3"
services:
    nginx:
        image: nginx:1.21-alpine
        ports:
            - 4000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - titumir
    postgres:
        image: postgres:13-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
            - /home/node/app/.docker
    redis:
        image: redis:6-alpine
        expose:
            - 6379
    titumir:
        build:
            context: ./
        links:
            - redis
        depends_on:
            - redis
            - postgres

volumes:
    pgdata:
