version: "3"
services:
  postgres:
    ports: 
      # only for development with vscode.sqltools
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=veschool
  titumir:
    ports: 
      - 9229:9229
    build:
      context: ./titumir
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app
      - /app/node_modules
    environment: 
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=veschool
      - NODE_ENV=development
      - DATABASE_USERNAME=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - NOT_A_SECRET=secretxxxxxsecret
      - PORT=4000
    # for using the container as a separate OS like
    command: sleep 50505050505