version: "3"
services:
    nginx:
        image: nginx:1.19.10-alpine
        ports:
            - 4000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - titumir
    postgres:
        image: postgres:13.3-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
            - /app/.docker
    titumir:
        build:
            context: ./
        depends_on:
            - postgres

volumes:
    pgdata:
