-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."user"
(
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    firstname character varying COLLATE pg_catalog."default" NOT NULL,
    lastname character varying COLLATE pg_catalog."default" NOT NULL,
    role_id uuid,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_id_fkey FOREIGN KEY (id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT user_role_id_fkey FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."user"
    OWNER to postgres;

GRANT ALL ON TABLE public."user" TO anon;

GRANT ALL ON TABLE public."user" TO authenticated;

GRANT ALL ON TABLE public."user" TO postgres;

GRANT ALL ON TABLE public."user" TO service_role;
