-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
ALTER TABLE IF EXISTS public."user"
ADD COLUMN school_id uuid;
ALTER TABLE IF EXISTS public."user"
ADD CONSTRAINT user_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.school (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.school
ALTER COLUMN owner_id
SET DEFAULT auth.uid();