-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.subject
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    updated_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    owner_id uuid NOT NULL,
    description text COLLATE pg_catalog."default",
    marks integer DEFAULT 100,
    CONSTRAINT cpk_subject PRIMARY KEY (id),
    CONSTRAINT "CUQ_subject_owner" UNIQUE (id, name, owner_id),
    CONSTRAINT subject_owner_id_fkey FOREIGN KEY (owner_id)
        REFERENCES public.grade (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.subject
    OWNER to postgres;

ALTER TABLE IF EXISTS public.subject
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.subject TO anon;

GRANT ALL ON TABLE public.subject TO authenticated;

GRANT ALL ON TABLE public.subject TO postgres;

GRANT ALL ON TABLE public.subject TO service_role;
